# Transcrit des captures PCS deposees dans second-brain/inbox/test pepiline/ le 2026-09-14.
EXPECTED = {
4: ["Pogacar Tadej","Widar Jarno","Gall Felix","Onley Oscar","Kuss Sepp","Mas Enric","Roglic Primoz","Carapaz Richard","Skjelmose Mattias","Muhlberger Gregor","Vine Jay","Debruyne Ramses","Tejada Harold","Torres Pablo","Brenner Marco","Berthet Clement","Hirt Jan","Ruiz Ibon","Tulett Ben","Omrzel Jakob","Svestad-Bardseng Embret","Pickering Finlay","Martin Guillaume","Rodriguez Cristian"],
7: ["Leknessund Andreas","Johannessen Tobias Halland","Van Aert Wout","Omrzel Jakob","Rodriguez Juan Felipe","Sosa Ivan Ramiro","Lutsenko Alexey","Dunbar Eddie","Bisiaux Leo","Garcia Pierna Raul","Paret-Peintre Valentin","Zana Filippo","Warbasse Larry","Martin Guillaume","Samitier Sergio","Pickering Finlay","Bouwman Koen","Wenzel Mats","Pogacar Tadej","Gall Felix","Mas Enric","Kuss Sepp","Roglic Primoz","Onley Oscar"],
10:["Tronchon Bastien","Cort Magnus","Nys Thibau","Van Aert Wout","Romele Alessandro","Azparren Xabier Mikel","Fisher-Black Finn","Aular Orluis","Labrosse Jordan","Hofstetter Hugo","Albanese Vincenzo","Fedorov Yevgeniy","Coquard Bryan","Bilbao Pello","Mulubrhan Henok","Laurance Axel","Camprubi Marcel","Glivar Gal","Carapaz Richard","Zana Filippo","Leemreize Gijs","Martin Guillaume","Kung Stefan","Gonzalez David"],
13:["Van Aert Wout","Paret-Peintre Valentin","Brennan Matthew","Widar Jarno","Albanese Vincenzo","Fisher-Black Finn","Vermaerke Kevin","Bisiaux Leo","Dalby Simon","Zana Filippo","Herrada Jesus","Kron Andreas","Samitier Sergio","Leemreize Gijs","Cobo Ivan","Moniquet Sylvain","Rodriguez Cristian","Warbasse Larry","Berthet Clement","Craps Lars","Dunbar Eddie","Martin Guillaume","Thompson Reuben","Skjelmose Mattias"],
16:["Brennan Matthew","Coquard Bryan","Braet Vito","Meeus Jordi","Cort Magnus","Van Aert Wout","Hofstetter Hugo","Albanese Vincenzo","Dainese Alberto","Macias Cesar","Camprubi Marcel","Brustenga Marc","Miquel Pau","De Jong Timo","Renard Alexis","Vader Milan","Fedorov Yevgeniy","Govekar Matevz","Romele Alessandro","Dversnes Lavik Fredrik","De Schuyteneer Steffen","Elosegui Inigo","Bouwman Koen","Le Gac Olivier"],
19:["Dunbar Eddie","Buitrago Santiago","Gloag Thomas","Berrade Urko","Camprubi Marcel","Leknessund Andreas","Martin Guillaume","Hamilton Chris","Vermaerke Kevin","Samitier Sergio","Molard Rudy","Gall Felix","Carapaz Richard","Roglic Primoz","Onley Oscar","Mas Enric","Omrzel Jakob","Berthet Clement","Kuss Sepp","Tejada Harold","Rodriguez Cristian","Bisiaux Leo","Aparicio Mario","Riccitello Matthew"],
20:["Landa Mikel","Johannessen Tobias Halland","Debruyne Ramses","Miquel Pau","Berrade Urko","Hirt Jan","Nordhagen Jorgen","Kuss Sepp","Calzoni Walter","Fortunato Lorenzo","Vermaerke Kevin","Widar Jarno","Gall Felix","Mas Enric","Roglic Primoz","Aparicio Mario","Sosa Ivan Ramiro","Carapaz Richard","Onley Oscar","Omrzel Jakob","Rodriguez Cristian","Martin Guillaume","Berthet Clement","Tejada Harold"],
}
